### ISSUE TITLE
Wiki updated - please review

### ISSUE THREAD

**Issue by dxwell** [geological-survey-of-queensland/gsq-info-model#1]
I have updated the process diagram to place peer review first.
Also added some additional technical checks at the bottom of the page.
Please review and comment.

**Comment by johnkirsten** [comment]
Looks good, thanks David

**Comment by GSQ-AI** [comment]
I think that this is a far better process than the original and represents all parties and processes faithfully. 

Has anyone run it past Mark Gordon yet?

**Comment by KellyVance** [comment]
This is a better flow and more intuitive. 
It could possibly be further optimised by having the technical check before the business check. Then the business check and publishing approval can be consolidated to a single process for the custodian. 
i.e.
from author>peer>custodian>technical>custodian>publish
to author>peer>technical>custodian>publish

**Comment by dxwell** [comment]
> This is a better flow and more intuitive.
> It could possibly be further optimised by having the technical check before the business check. Then the business check and publishing approval can be consolidated to a single process for the custodian.
> i.e.
> from author>peer>custodian>technical>custodian>publish
> to author>peer>technical>custodian>publish

@KellyVance like this? Much simpler workflow 
![Wiki Diagrams - Profile Review Process](https://user-images.githubusercontent.com/47203106/63983086-8438c280-cb08-11e9-937f-c23a96319d01.png)

**Comment by KellyVance** [comment]
Perfect.

**Comment by dxwell** [comment]
> Has anyone run it past Mark Gordon yet?

Not yet @GSQ-AI - but please do when we are happy with the final version.
