### ISSUE TITLE
Review 'How to request a profile review'

### ISSUE THREAD

**Issue by dxwell** [geological-survey-of-queensland/gsq-info-model#2]
Please review the wiki page **How to request a profile review**
https://github.com/geological-survey-of-queensland/gsq-info-model/wiki/How-to-request-a-profile-review

**Comment by johnkirsten** [comment]
For the final review step, Data Custodian Review, the github process is essentially the same as the preceding review steps and only changes in name. My view is that this final review should be made by reviewing a summary of the profile and the outcomes of the preceding reviews by the data managers and content authorities. Rather than asking the custodians to create branches and pull requests we should ask them to either formally approve or to request changes/further information by way of written feedback. This final approval step should be for a custodian who is already across the approach being taken and is therefore formality step that should be simplified.

**Comment by dxwell** [comment]
> Rather than asking the custodians to create branches and pull requests

The custodian does not create a branch or pull request. The content authority does all branches and pull requests.

> request changes/further information by way of written feedback

This means that we have their approval outside of our workflow system (Github). In 5 year's time, we should be able to see the full audit trail of reviews, comments, and approvals.
I think custodians will be capable of responding to the request from Github.

**Comment by johnkirsten** [comment]
> The custodian does not create a branch or pull request. The content authority does all branches and pull requests.

I cant see where it says who should be performing these activities. Also, I thought that it was going to the data manager responsibility to not only create profiles (in lucid chart, github etc) but to also oversee and manage this review process.



> This means that we have their approval outside of our workflow system (Github). In 5 year's time, we should be able to see the full audit trail of reviews, comments, and approvals.
> I think custodians will be capable of responding to the request from Github.

Apologies, but I was suggesting written feedback within the github workflow, defintely not outside of it.

**Comment by dxwell** [comment]
> data manager responsibility to not only create profiles (in lucid chart, github etc) but to also oversee and manage this review process

It's a good question. There are advantages to data managers doing it. My thinking was that the data custodians could do this.
@KellyVance what are your thoughts?

**Comment by KellyVance** [comment]
I do like leaving more of the actual _GitHub_ process in the hands of the data managers as an enabler of oversight. Acknowledging that parts of the _business_ process are recorded in GitHub but not necessarily a function of GitHub. I wonder if even the initial branch creation should be a data manager role for the content authorities to then populate/edit.

**Comment by DavidCrosswellGSQ** [comment]
> leaving more of the actual _GitHub_ process in the hands of the data managers
> initial branch creation should be a data manager role

Agree - the whole github creating and pull requesting and merging can be done by the Data Managers. The instructions are open as to who performs the githubbing. That way, we can cater for a technically proficient data authority who wants to do the githubbing able to do it.

**Comment by GSQ-AI** [comment]
I'm in favour of following a protocol which limits the exposure of the _Content Authorities_ to the vagaries of GitHub. 

In general, I'd prefer for them to be focussed on the task of creating/editing/reviewing the profile, which is a big enough issue as it is without introducing a second layer of complexity.

**Comment by dxwell** [comment]
Data managers will drive Github, creating branches and pull requests.
However, I will leave this out of the instructions as there is likely to be some non-data manager users who will have the skill to drive Github.
