### ISSUE TITLE
Review 'How to create a dataset profile'

### ISSUE THREAD

**Issue by dxwell** [geological-survey-of-queensland/gsq-info-model#3]
Please review the wiki page **How to create a dataset profile**

https://github.com/geological-survey-of-queensland/gsq-info-model/wiki/How-to-create-a-dataset-profile

**Comment by johnkirsten** [comment]
Looks good.

**Comment by KellyVance** [comment]
A good straight-forward description.
When we have a profile to do I can do a test and see if there are any sticking points

**Comment by GSQ-AI** [comment]
I can't see any glaring issues with the process, either. 

However, a mechanical problem may arise when reviewers are commenting on the diagrams - as @KellyVance and I had discussed earlier in the piece. Being limited to textually describing items in an image **sucks**. We may be able to avoid or limit these problems by mandating the inclusion of a OneDrive/Sharepoint/LucidChart link to the diagram to comment on, as was tested earlier.

**Comment by dxwell** [comment]
Reviewers will comment on the diagrams in Lucidchart using the comment function - see https://www.lucidchart.com/pages/videos/how-to-use-comments

A link to the Lucidchart diagram is to be provided by the person requesting the review.
